project:
  type: website
  output-dir: docs

website:
  title: "Theta Biomarkers"
  navbar:
    left:
      - text: Processing
        href: data_desc_040624.qmd
      - modeling_110624.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

